name: goals-app
services:
    backend:
        networks:
            - goals
        container_name: backend
        ports:
            - 80:80
        volumes:
            - logs:/logs
        environment:
            - MONGODB_USERNAME=mongoadmin
            - MONGODB_PASSWORD=secret
        image: vgeorgiev99/backend
    frontend:
        networks:
            - goals
        container_name: frontend
        ports:
            - 3000:3000
        volumes:
            - ./frontend/src:/src
        image: vgeorgiev99/frontend
    mongo:
        networks:
            - goals
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - data:/data/db
        image: mongo
networks:
    goals:
        name: goals
volumes:
    logs:
        name: logs
    data:
        name: data