name: House-Renting-System CI

on:
  push:
    branches: [ "house-renting-system-prod" ]
  pull_request:
    branches: [ "house-renting-system-prod" ]  

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
        # Setup .NET SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build .NET
      run: dotnet build
    - name: Test .NET
      run: dotnet test