# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI-CD Student Registry App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: CI-CD/01-02-Student-Registry-App/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: CI-CD/01-02-Student-Registry-App
    - name: Excecute the tests
      run: npm test
      working-directory: CI-CD/01-02-Student-Registry-App
  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: CI-CD/01-02-Student-Registry-App/package-lock.json
    - name: Deploy to Render.com
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.SERVICE_ID }}
        api_key: ${{ secrets.RENDER_TOKEN }}  
        wait_deploy: true
      